version: '3'
services:
  workspace:
    build:
      context: ./docker/workspace
    restart: always
    volumes:
      - ./:/opt/ci123/www/html
    env_file:
      - docker.env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  lnmp:
    build:
      context: ./docker/lnmp
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/opt/ci123/www/html
    env_file:
      - docker.env
    depends_on:
      - mysql
      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  mysql:
    image: mysql:5.7.22
    restart: always
    volumes:
      - ./storage/app/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=deploy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  rabbitmq:
    image: bitnami/rabbitmq:3.7
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=ci@123
