metadata:
  name: name
  labels:
    app: app
spec:
  template:
    spec:
      containers:
      - name: job
        image: image
        volumeMounts:
        - name: data
          mountPath: mountPath
      restartPolicy: OnFailure
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: claimName
  backoffLimit: 0