apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployv2
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Gi
