metadata:
  name: name
  labels:
    app: app
spec:
  serviceName: serviceName
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      initContainers:
      - name: clone-mysql
        image: registry-gcr-io.oneitfarm.com/google-samples/xtrabackup:1.0
        command:
          - bash
          - /mnt/config-map/clone-mysql.sh
        env:
        - name: name
          value: value
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      - name: init-mysql
        image: mysql:5.7.22
        command:
          - bash
          - /mnt/config-map/init-mysql.sh
        volumeMounts:
          - name: conf
            mountPath: /mnt/conf.d
          - name: config-map
            mountPath: /mnt/config-map
          - name: scripts
            mountPath: /mnt/scripts
      containers:
      - name: mysql
        image: mysql:5.7.22
        env:
        - name: name
          value: value
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1024Mi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - "-c"
            - MYSQL_PWD="${MYSQL_ROOT_PASSWORD}"
            - mysql -h 127.0.0.1 -u root -e "SELECT 1"
          initialDelaySeconds: 10
          timeoutSeconds: 1
      - name: xtrabackup
        image: registry-gcr-io.oneitfarm.com/google-samples/xtrabackup:1.0
        env:
        - name: name
          value: value
        ports:
        - name: xtrabackup
          containerPort: 3307
        command:
        - bash
        - /mnt/config-map/xtrabackup.sh
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-map
          mountPath: /mnt/config-map
        - name: scripts
          mountPath: /mnt/scripts
        resources:
          requests:
            cpu: 1m
            memory: 100Mi
      volumes:
      - name: config-map
        configMap:
          name: name
      - name: conf
        emptyDir: {}
      - name: scripts
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: app
    spec:
      accessModes:
      - ReadWriteOnce
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs-ssd
