metadata:
  name: name
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: name
      containers:
      - name: workspace
        imagePullPolicy: Always
        image: image
        volumeMounts:
        - mountPath: mountPath
          name: envs-volume
        - mountPath: /opt/ci123/www/html
          name: code-data
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        env:
        - name: name
          value: value
        envFrom:
        - configMapRef:
            name: name
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
      volumes:
      - name: code-data
        persistentVolumeClaim:
          claimName: claimName
      - name: envs-volume
        configMap:
          name: name